config/routes.rb
Rails.application.routes.draw do

  patch "/posts/:id/favourite", to: "posts#favourite", as: :new_favourite_word

  # devise_for :users, :controllers => { :registrations => :registrations }

  resources :posts do 
    resources :comments
  end

  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/create'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/destroy'
  get 'search', to: "posts#search"

  resources :categories
  devise_for :users
  resources :users
  resources :tags
 

  root "categories#index"

  # namespace :user do
  #     root :to => "users#show"
  # end

  # get '/user' => "users#index", :as => :user_root

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :pronunciation
    belongs_to :user
    has_many :comments
    has_and_belongs_to_many :tags
   
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :nav_tags
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    if current_user
      @comment = Comment.new
      @user = User.find(current_user.id)
      @posts = @user.posts
    end
  end

  def favourite
  # find post from id
    @post = Post.find(params[:id])
    @current_user_found= User.find(current_user.id)
    
    if @current_user_found.favourite_words.include?(@post.id.to_s)
     #if user has already favourited prompt error
      redirect_to post_path(@post), alert: "Already favourited this word"
    else
      
      @current_user_found.favourite_words << @post.id
      if @current_user_found.save

        redirect_to post_path(@post), notice: "You favourited this word"
      else
          redirect_to post_path(@post), notice: "Try again"
      end
    end

    
    # if @current_user_found.favourite_words.include?(@post.id.to_s)
    #  #if user has already favourited prompt error
    #   redirect_to post_path(@post.id), alert: "Already favourited this word"
    # else
      
    #   @current_user_found.favourite_words << @post.id
    #   if @current_user_found.save

    #     redirect_to post_path(@post.id), notice: "You favourited this word"
    #   else
    #       redirect_to post_path(@post.id), notice: "Try again"
    #   end
    # end
  end

  def word_of_day
    @post = Post.where(word_of_day: true)
  end

  # search function; turns table col to downcase, matches query.downcase
  def search
    @posts = Post.order("lower(word) ASC").where(
      Post.arel_table[:word]
      .lower
      .matches("%#{params[:query].downcase}%")
    )
  end

  # GET /posts/new
  def new
    @post = Post.new
  end


  def follow
    # find user from id
    @user = User.find(params[:id])

    @current_user_found= User.find(current_user.id)
    
    if @current_user_found.following.include?(@user.id.to_s)
     #if user is already following prompt error
      redirect_to show_profile_path(@user.id), alert: "Already Following this user"
    else
      
      @current_user_found.following << @user.id
      if @current_user_found.save

        redirect_to show_profile_path(@user.id), notice: "Now following user"
      else
          redirect_to show_profile_path(@user.id), notice: "couldnot follow user"
      end
    end
  end
  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @post['user_id'] = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post['user_id'] = current_user.id
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:word, :description, :example, :pronunciation, :meaning, tag_ids: [])
    end

    def nav_tags
      @tags = Tag.all
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container-fluid">
  <div class="row">
    
    <div class="col-3 addNewWord">
      <u>add <br> a new <br> word</u>
    </div>

  
    <div class="col-8 mt-4">

      <div class="row mb-4">
        <div class="col-3 text-right">
          <div>
            <%= form.label :word, class: "perFieldFont" %>
          </div>
        </div>

        <div class="col-9">
          <div class="perField">
            <%= form.text_area :word, cols: "70" %>
          </div>
        </div>
      </div>

      <div class="row mb-4">
        <div class="col-3 text-right">
          <div>
            <%= form.label :meaning, class: "perFieldFont" %>
          </div>
        </div>

        <div class="col-9">
          <div class="perField">
            <%= form.text_area :meaning, cols: "70" %>
          </div>
        </div>
      </div>

      <div class="row mb-4">
        <div class="col-3 text-right">
          <div>
            <%= form.label :description, class: "perFieldFont" %>
          </div>
        </div>

        <div class="col-9">
          <div class="perField">
          <%= form.text_area :description, cols: "70" %>
          </div>
        </div>
      </div>

      <div class="row mb-4">
        <div class="col-3 text-right">
          <div>
            <%= form.label :example, class: "perFieldFont" %>
          </div>
        </div>

        <div class="col-9">
          <div class="perField">
            <%= form.text_area :example, cols: "70" %>
          </div>
        </div>
      </div>

      <div class="row mb-4">
        <div class="col-3 text-right">
          <div>
            <%= form.label :pronunciation, class: "perFieldFont" %> 
          </div>
        </div>

        <div class="col-9">
          <div class=“perField”>
            <%= form.file_field :pronunciation, cols: "70" %> 
          </div>
        </div>
      </div>

      <div class="row mb-4">
        <div class="col-3 text-right">
          <div class="perFieldFont">
             <p>Select tag</p>
          </div>
        </div>

        <div class="col-9">
          <div class="perField pt-3 mr-2">
            <%= collection_check_boxes(:post, :tag_ids, Tag.all, :id, :name) %>
          
          </div>
        </div>
      

       <div class="row mb-4">
        <div class="col-12">
          <div class="perField">
            <%= form.submit class: "btn btn-sm-primary" %>
          </div>
        </div>
      </div>

  </div>
</div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>




    <% @posts.each do |post| %>

       <%= post.word %>
      
      <%= link_to post.word, post %>
     
       

    <% end %>
 

app/views/posts/new.html.erb
<%# <h1>add a new word</h1> %>

<%= render 'form', post: @post%>

app/views/posts/search.html.erb
<h1>Search results for: "<%= params[:query] %>"</h1>    

<div class="row mt-5 ml-1">
    <% if @posts[0] %>
        <% @posts.each do |post| %>
        <div class="col-4 wordsByAlphabet mb-5">               
            <%= link_to post.word, post_path(post) %>
        </div>
    <% end %>
    <% else %>
        <em>Got nothing leh.</em>
    <% end %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container-fluid">

  <div class="row">

    <div class="col-3 addNewWord">
      <p><u><%= @post.word %></u></p>
      
      
          <%# if user_signed_in? %>
            <%#= form_for @post, url: new_favourite_word_path(@post.id) do |f| %>
              <%#= f.submit "favourite this word", class: "btn btn-primary" %>
            <%# end %>
          <%# end %>
      

      <br> <% if @post.user.id == current_user.id %>
            <p class="commentFont"> <%= link_to 'Edit', edit_post_path(@post) %> </p>
          <% end %>
    </div>


      <%# main text container %>
      <div class="col-8 mt-4"> 
      
        <%# means %>
        <div class="row mb-3">
          <div class="col-3 perFieldFont">
            <p>means:</p>
          </div>

          <div class="col-9">
            <%= @post.description %>
          </div>
        </div>
    
        <%# pronunciation %>
        <div class="row mb-3">
          <div class="col-3 perFieldFont">
              <p>pronunciation: </p>
          </div>
          <div class="col-9">
            <% if @post.pronunciation.attached? %>
                  <%=audio_tag (url_for(@post.pronunciation)), controls:"play" %>
                <% end %>
          </div>

        </div>

        <%# example %>
        <div class="row mb-3">
          <div class="col-3 perFieldFont">
            <p>used in sentence:</p>
          </div>
          
          <div class="col-9">
            <%= @post.example %>
          </div>
        </div>

        <%# tags %>
        <div class="row mb-3">
          <div class="col-3 perFieldFont">
          <p>tags:</p>
          </div>

          <div class="col-9">
            <p><% @post.tags.each do |tag| %>
                <td><%= link_to tag.name, tag_path(tag) %></td>
              <% end %> 
            </p>
          </div>
        </div>

        <%# tags %>
        <div class="row mb-3">
          <div class="col-3 perFieldFont">
          <p>contributed by:</p>
          </div>

          <div class="col-9">
            <p><%= link_to @post.user.username, user_path(@post.user.id) %>
            </p>
          </div>
        </div>
          
        <%# comment %>
        <div class="row mb-3">
          <div class="col-12">         
            <p class="perFieldFont">comments: </p>

            <% @post.comments.each do |comment| %>                            

              <div class="media text-muted pt-3 w-100">
                <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray w-75">

                  <% if user_signed_in? %>
                    <% if current_user.profile_pic.attached? %>
                      <%= image_tag (comment.user.profile_pic), :style => "border: 3px solid #9B6A6C; border-radius: 50%;", width: 50, height: "auto" %>
                    <% end %>
                  <% end %> 
                  
                    
                  <strong class="d-block text-gray-dark mb-3"><%= comment.user.username %> @ <%= comment.created_at.strftime("%d %b %Y, %I:%M%p") %></strong>
                  <%= comment.comments %>
                </p>
              </div>
            <% end %>

              <div class="container pb-cmnt-container mt-3">
                <div class="row">
                  <div class="col-md-6 col-md-offset-3">
                    <div class="panel panel-info">
                      <div class="panel-body">
                      <% if current_user %>
                        <%= form_for [@post, @comment], html: {class: ""} do |f| %>
                              
                        <%= f.text_area :comments, placeholder:"Write your comment here!", class: "form-control" %>
                              
                        <%= f.submit "Comment", class: "btn btn-sm btn-primary mt-2 mb-5" %>
                              
                        <% end %>
                      </div>
                      <% end %>
                        
                    </div>
                  </div>
                </div>
              </div>

          </div>
        </div>
          
      </div>

  </div>
</div>