config/routes.rb
Rails.application.routes.draw do

  patch "/posts/:id/favourite", to: "posts#favourite", as: :new_favourite_word

  # devise_for :users, :controllers => { :registrations => :registrations }

  resources :posts do 
    resources :comments
  end

  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/create'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/destroy'
  get 'search', to: "posts#search"

  resources :categories
  devise_for :users
  resources :users
  resources :tags
 

  root "categories#index"

  # namespace :user do
  #     root :to => "users#show"
  # end

  # get '/user' => "users#index", :as => :user_root

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :nav_tags
  def index
    @posts = Post.all
  end

  def show
    @posts = Post.all.order("lower(word) ASC").select { |post| post.word[0].upcase === params[:id].upcase } # selects only posts start with letter in URL query
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def nav_tags
    @tags = Tag.all
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<%# create index of all letters in alphabets %>
<ul class="oneAlphabet">
    <% ("a".."z").each do |letter| %>
        <%= link_to letter.upcase, category_path(letter) %>
    <% end %>
    <%= link_to "1-9", category_path("1-9") %>
</ul>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<div class="row mt-5">
    <div class="col-3 oneAlphabet" style="color: #9B6A6C"><%= params[:id].upcase %></div>
    <div class="col-9">
        <div class="row">
            <% @posts.each do |post| %>
                <div class="col-4 wordsByAlphabet mb-5">
                    <%= link_to post.word.downcase, post_path(post) %>
                </div>
            <% end %>
        </div>
    </div>
    </div>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>