config/routes.rb
Rails.application.routes.draw do

  patch "/posts/:id/favourite", to: "posts#favourite", as: :new_favourite_word

  # devise_for :users, :controllers => { :registrations => :registrations }

  resources :posts do 
    resources :comments
  end

  # get 'users/index'
  # get 'users/show'
  # get 'users/new'
  # get 'users/create'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/destroy'
  get 'search', to: "posts#search"

  resources :categories
  devise_for :users
  resources :users
  resources :tags
 

  root "categories#index"

  # namespace :user do
  #     root :to => "users#show"
  # end

  # get '/user' => "users#index", :as => :user_root

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Singlish</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style.css' %>    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,700;0,800;1,400;1,500;1,700;1,800&display=swap" rel="stylesheet">

  </head>

  <body>

    <% if notice %>
    <p class="alert alert-success notice mb-0"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger mb-0"><%= alert %></p>
    <% end %>

    <%# navbar %>
    <div class="navbarStyling">
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        
        <%#= link_to "Singlish", categories_path, class: "navbar-brand text-light" %> 

        <%# Logo %>
        <%= link_to categories_path do %> 
        <%= image_tag ("logo_white.png"), width: 100, height: "auto", class: "mr-5" %> 
        <% end %>

        <%# search bar %>
        <form action="/search" class="form-inline my-2 my-lg-0 mr-3">
          <input class="clear search-bar bg-dark form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search" style="border-radius: 0;">
        </form>


        <%# random word %>
        <div class="collapse navbar-collapse justify-content-end" id="navbarText">
          <span class="navbar-text">
              <%= link_to "Random Word", post_path(Post.all.sample), class: "nav-link text-light" %>
          </span>
        </div>


        <%# tags %>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Tags
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% Tag.all.each do |tag| %>
              <a class="dropdown-item" href= "<%= tag_path(tag) %>" > <%= tag.name %></a>
            <% end %>
          </div>
        </div>

        
      <%# log in / log out buttons %>
          <% if user_signed_in? %>
            <div class="nav-item dropdown">
            <% if current_user.profile_pic.attached? %>
              <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= image_tag (current_user.profile_pic), :style => "border: 2px solid white; border-radius: 50%;", width: 40, height: "auto" %>
              </a>
            <% else %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
            <% end %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href= <%= user_path(current_user.id) %> >Profile</a>
                <a class="dropdown-item" href="#">Favourites</a>
                <a class="dropdown-item" href= <%= new_post_path%> >Add New Word</a>
                <a class="dropdown-item"<%= link_to "Log out", destroy_user_session_path, method: :delete%></a>
              </div>
            </div>
              
          <% end %> 
      

        <ul class="nav justify-content-end">
            <% if !user_signed_in? %>
              <%= link_to  "Log in", new_user_session_path, class: "nav-link text-light" %>
            <% end %> 
        </ul>
      </div>

    <%= yield %>
  </body>
</html>